<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AddonSettingTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('addon_settings')->truncate();
        $chunks = [];
        $chunks[] =
            array (
              0 => 
              array (
                'id' => '070c6bbd-d777-11ed-96f4-0c7a158e4469',
                'key_name' => 'twilio',
                'live_values' => '{"gateway":"twilio","mode":"live","status":"0","sid":"data","messaging_service_sid":"data","token":"data","from":"data","otp_template":"data"}',
                'test_values' => '{"gateway":"twilio","mode":"live","status":"0","sid":"data","messaging_service_sid":"data","token":"data","from":"data","otp_template":"data"}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 13:01:29',
                'additional_data' => '',
              ),
              1 => 
              array (
                'id' => '070c766c-d777-11ed-96f4-0c7a158e4469',
                'key_name' => '2factor',
                'live_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":"data"}',
                'test_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":"data"}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 13:01:36',
                'additional_data' => '',
              ),
              2 => 
              array (
                'id' => '0d8a9308-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'mercadopago',
                'live_values' => '{"gateway":"mercadopago","mode":"live","status":0,"access_token":"","public_key":""}',
                'test_values' => '{"gateway":"mercadopago","mode":"live","status":0,"access_token":"","public_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-27 17:57:11',
                'additional_data' => '{"gateway_title":"Mercadopago","gateway_image":null}',
              ),
              3 => 
              array (
                'id' => '0d8a9e49-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'liqpay',
                'live_values' => '{"gateway":"liqpay","mode":"live","status":0,"private_key":"","public_key":""}',
                'test_values' => '{"gateway":"liqpay","mode":"live","status":0,"private_key":"","public_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:32:31',
                'additional_data' => '{"gateway_title":"Liqpay","gateway_image":null}',
              ),
              4 => 
              array (
                'id' => '101befdf-d44b-11ed-8564-0c7a158e4469',
                'key_name' => 'paypal',
                'live_values' => '{"gateway":"paypal","mode":"live","status":"0","client_id":"","client_secret":""}',
                'test_values' => '{"gateway":"paypal","mode":"live","status":"0","client_id":"","client_secret":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 09:41:32',
                'additional_data' => '{"gateway_title":"Paypal","gateway_image":null}',
              ),
              5 => 
              array (
                'id' => '133d9647-cabb-11ed-8fec-0c7a158e4469',
                'key_name' => 'hyper_pay',
                'live_values' => '{"gateway":"hyper_pay","mode":"test","status":"0","entity_id":"data","access_code":"data"}',
                'test_values' => '{"gateway":"hyper_pay","mode":"test","status":"0","entity_id":"data","access_code":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:32:42',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              6 => 
              array (
                'id' => '1821029f-d776-11ed-96f4-0c7a158e4469',
                'key_name' => 'msg91',
                'live_values' => '{"gateway":"msg91","mode":"live","status":"0","template_id":"data","auth_key":"data"}',
                'test_values' => '{"gateway":"msg91","mode":"live","status":"0","template_id":"data","auth_key":"data"}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 13:01:48',
                'additional_data' => '',
              ),
              7 => 
              array (
                'id' => '18210f2b-d776-11ed-96f4-0c7a158e4469',
                'key_name' => 'nexmo',
                'live_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 08:14:44',
                'additional_data' => '',
              ),
              8 => 
              array (
                'id' => '18fbb21f-d6ad-11ed-962c-0c7a158e4469',
                'key_name' => 'foloosi',
                'live_values' => '{"gateway":"foloosi","mode":"test","status":"0","merchant_key":"data"}',
                'test_values' => '{"gateway":"foloosi","mode":"test","status":"0","merchant_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:34:33',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              9 => 
              array (
                'id' => '2767d142-d6a1-11ed-962c-0c7a158e4469',
                'key_name' => 'paytm',
                'live_values' => '{"gateway":"paytm","mode":"live","status":0,"merchant_key":"","merchant_id":"","merchant_website_link":""}',
                'test_values' => '{"gateway":"paytm","mode":"live","status":0,"merchant_key":"","merchant_id":"","merchant_website_link":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-22 12:30:55',
                'additional_data' => '{"gateway_title":"Paytm","gateway_image":null}',
              ),
              10 => 
              array (
                'id' => '3201d2e6-c937-11ed-a424-0c7a158e4469',
                'key_name' => 'amazon_pay',
                'live_values' => '{"gateway":"amazon_pay","mode":"test","status":"0","pass_phrase":"data","access_code":"data","merchant_identifier":"data"}',
                'test_values' => '{"gateway":"amazon_pay","mode":"test","status":"0","pass_phrase":"data","access_code":"data","merchant_identifier":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:36:07',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              11 => 
              array (
                'id' => '33a90207-7315-4bfe-a9af-d16049cc0b7c',
                'key_name' => 'cashfree',
                'live_values' => '"{\\"gateway\\":\\"cashfree\\",\\"mode\\":\\"test\\",\\"status\\":0,\\"client_id\\":\\"\\",\\"client_secret\\":\\"\\"}"',
                'test_values' => '"{\\"gateway\\":\\"cashfree\\",\\"mode\\":\\"test\\",\\"status\\":0,\\"client_id\\":\\"\\",\\"client_secret\\":\\"\\"}"',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => '2024-12-21 12:51:28',
                'updated_at' => '2024-12-21 12:51:28',
                'additional_data' => '',
              ),
              12 => 
              array (
                'id' => '4593b25c-d6a1-11ed-962c-0c7a158e4469',
                'key_name' => 'paytabs',
                'live_values' => '{"gateway":"paytabs","mode":"live","status":0,"profile_id":"","server_key":"","base_url":"https:\\/\\/secure-egypt.paytabs.com\\/"}',
                'test_values' => '{"gateway":"paytabs","mode":"live","status":0,"profile_id":"","server_key":"","base_url":"https:\\/\\/secure-egypt.paytabs.com\\/"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:34:51',
                'additional_data' => '{"gateway_title":"Paytabs","gateway_image":null}',
              ),
              13 => 
              array (
                'id' => '4e9b8dfb-e7d1-11ed-a559-0c7a158e4469',
                'key_name' => 'bkash',
                'live_values' => '{"gateway":"bkash","mode":"live","status":"0","app_key":"","app_secret":"","username":"","password":""}',
                'test_values' => '{"gateway":"bkash","mode":"live","status":"0","app_key":"","app_secret":"","username":"","password":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:39:42',
                'additional_data' => '{"gateway_title":"Bkash","gateway_image":null}',
              ),
              14 => 
              array (
                'id' => '544a24a4-c872-11ed-ac7a-0c7a158e4469',
                'key_name' => 'fatoorah',
                'live_values' => '{"gateway":"fatoorah","mode":"test","status":"0","api_key":"data"}',
                'test_values' => '{"gateway":"fatoorah","mode":"test","status":"0","api_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:36:24',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              15 => 
              array (
                'id' => '58c1bc8a-d6ac-11ed-962c-0c7a158e4469',
                'key_name' => 'ccavenue',
                'live_values' => '{"gateway":"ccavenue","mode":"test","status":"0","merchant_id":"data","working_key":"data","access_code":"data"}',
                'test_values' => '{"gateway":"ccavenue","mode":"test","status":"0","merchant_id":"data","working_key":"data","access_code":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 09:42:38',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-13-643783f01d386.png"}',
              ),
              16 => 
              array (
                'id' => '5e2d2ef9-d6ab-11ed-962c-0c7a158e4469',
                'key_name' => 'thawani',
                'live_values' => '{"gateway":"thawani","mode":"test","status":"0","public_key":"data","private_key":"data"}',
                'test_values' => '{"gateway":"thawani","mode":"test","status":"0","public_key":"data","private_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:50:40',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-13-64378f9856f29.png"}',
              ),
              17 => 
              array (
                'id' => '60cc83cc-d5b9-11ed-b56f-0c7a158e4469',
                'key_name' => 'sixcash',
                'live_values' => '{"gateway":"sixcash","mode":"test","status":"0","public_key":"data","secret_key":"data","merchant_number":"data","base_url":"data"}',
                'test_values' => '{"gateway":"sixcash","mode":"test","status":"0","public_key":"data","secret_key":"data","merchant_number":"data","base_url":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:16:17',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-12-6436774e77ff9.png"}',
              ),
              18 => 
              array (
                'id' => '68579846-d8e8-11ed-8249-0c7a158e4469',
                'key_name' => 'alphanet_sms',
                'live_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}',
                'test_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              19 => 
              array (
                'id' => '6857a2e8-d8e8-11ed-8249-0c7a158e4469',
                'key_name' => 'sms_to',
                'live_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}',
                'test_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              20 => 
              array (
                'id' => '74c30c00-d6a6-11ed-962c-0c7a158e4469',
                'key_name' => 'hubtel',
                'live_values' => '{"gateway":"hubtel","mode":"test","status":"0","account_number":"data","api_id":"data","api_key":"data"}',
                'test_values' => '{"gateway":"hubtel","mode":"test","status":"0","account_number":"data","api_id":"data","api_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:37:43',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              21 => 
              array (
                'id' => '74e46b0a-d6aa-11ed-962c-0c7a158e4469',
                'key_name' => 'tap',
                'live_values' => '{"gateway":"tap","mode":"test","status":"0","secret_key":"data"}',
                'test_values' => '{"gateway":"tap","mode":"test","status":"0","secret_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:50:09',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              22 => 
              array (
                'id' => '761ca96c-d1eb-11ed-87ca-0c7a158e4469',
                'key_name' => 'swish',
                'live_values' => '{"gateway":"swish","mode":"test","status":"0","number":"data"}',
                'test_values' => '{"gateway":"swish","mode":"test","status":"0","number":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:17:02',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              23 => 
              array (
                'id' => '7b1c3c5f-d2bd-11ed-b485-0c7a158e4469',
                'key_name' => 'payfast',
                'live_values' => '{"gateway":"payfast","mode":"test","status":"0","merchant_id":"data","secured_key":"data"}',
                'test_values' => '{"gateway":"payfast","mode":"test","status":"0","merchant_id":"data","secured_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:18:13',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              24 => 
              array (
                'id' => '8592417b-d1d1-11ed-a984-0c7a158e4469',
                'key_name' => 'esewa',
                'live_values' => '{"gateway":"esewa","mode":"test","status":"0","merchantCode":"data"}',
                'test_values' => '{"gateway":"esewa","mode":"test","status":"0","merchantCode":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:17:38',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              25 => 
              array (
                'id' => '888e7b84-27b3-497d-a5ef-cd69d65a798e',
                'key_name' => 'instamojo',
                'live_values' => '"{\\"gateway\\":\\"instamojo\\",\\"mode\\":\\"test\\",\\"status\\":\\"0\\",\\"client_id\\":\\"\\",\\"client_secret\\":\\"\\"}"',
                'test_values' => '"{\\"gateway\\":\\"instamojo\\",\\"mode\\":\\"test\\",\\"status\\":\\"0\\",\\"client_id\\":\\"\\",\\"client_secret\\":\\"\\"}"',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => '2024-12-21 12:51:28',
                'updated_at' => '2024-12-21 12:51:28',
                'additional_data' => '',
              ),
              26 => 
              array (
                'id' => '9162a1dc-cdf1-11ed-affe-0c7a158e4469',
                'key_name' => 'viva_wallet',
                'live_values' => '{"gateway":"viva_wallet","mode":"test","status":"0","client_id": "","client_secret": "", "source_code":""} ',
                'test_values' => '{"gateway":"viva_wallet","mode":"test","status":"0","client_id": "","client_secret": "", "source_code":""} ',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              27 => 
              array (
                'id' => '998ccc62-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'stripe',
                'live_values' => '{"gateway":"stripe","mode":"live","status":"0","api_key":null,"published_key":null}',
                'test_values' => '{"gateway":"stripe","mode":"live","status":"0","api_key":null,"published_key":null}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:18:55',
                'additional_data' => '{"gateway_title":"Stripe","gateway_image":null}',
              ),
              28 => 
              array (
                'id' => 'a3313755-c95d-11ed-b1db-0c7a158e4469',
                'key_name' => 'iyzi_pay',
                'live_values' => '{"gateway":"iyzi_pay","mode":"test","status":"0","api_key":"data","secret_key":"data","base_url":"data"}',
                'test_values' => '{"gateway":"iyzi_pay","mode":"test","status":"0","api_key":"data","secret_key":"data","base_url":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:20:02',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              29 => 
              array (
                'id' => 'a76c8993-d299-11ed-b485-0c7a158e4469',
                'key_name' => 'momo',
                'live_values' => '{"gateway":"momo","mode":"live","status":"0","api_key":"data","api_user":"data","subscription_key":"data"}',
                'test_values' => '{"gateway":"momo","mode":"live","status":"0","api_key":"data","api_user":"data","subscription_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:19:28',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              30 => 
              array (
                'id' => 'a8608119-cc76-11ed-9bca-0c7a158e4469',
                'key_name' => 'moncash',
                'live_values' => '{"gateway":"moncash","mode":"test","status":"0","client_id":"data","secret_key":"data"}',
                'test_values' => '{"gateway":"moncash","mode":"test","status":"0","client_id":"data","secret_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:47:34',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              31 => 
              array (
                'id' => 'ad5af1c1-d6a2-11ed-962c-0c7a158e4469',
                'key_name' => 'razor_pay',
                'live_values' => '{"gateway":"razor_pay","mode":"live","status":"0","api_key":null,"api_secret":null}',
                'test_values' => '{"gateway":"razor_pay","mode":"live","status":"0","api_key":null,"api_secret":null}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:47:00',
                'additional_data' => '{"gateway_title":"Razor pay","gateway_image":null}',
              ),
              32 => 
              array (
                'id' => 'ad5b02a0-d6a2-11ed-962c-0c7a158e4469',
                'key_name' => 'senang_pay',
                'live_values' => '{"gateway":"senang_pay","mode":"live","status":"0","callback_url":null,"secret_key":null,"merchant_id":null}',
                'test_values' => '{"gateway":"senang_pay","mode":"live","status":"0","callback_url":null,"secret_key":null,"merchant_id":null}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-27 15:58:57',
                'additional_data' => '{"gateway_title":"Senang pay","gateway_image":null}',
              ),
              33 => 
              array (
                'id' => 'b043c880-874b-4ee7-b945-b19e3bb2cabc',
                'key_name' => 'phonepe',
                'live_values' => '"{\\"gateway\\":\\"phonepe\\",\\"mode\\":\\"test\\",\\"status\\":0,\\"merchant_id\\":\\"\\",\\"salt_Key\\":\\"\\",\\"salt_index\\":\\"\\"}"',
                'test_values' => '"{\\"gateway\\":\\"phonepe\\",\\"mode\\":\\"test\\",\\"status\\":0,\\"merchant_id\\":\\"\\",\\"salt_Key\\":\\"\\",\\"salt_index\\":\\"\\"}"',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => '2024-12-21 12:51:28',
                'updated_at' => '2024-12-21 12:51:28',
                'additional_data' => '',
              ),
              34 => 
              array (
                'id' => 'b6c333f6-d8e9-11ed-8249-0c7a158e4469',
                'key_name' => 'akandit_sms',
                'live_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}',
                'test_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              35 => 
              array (
                'id' => 'b6c33c87-d8e9-11ed-8249-0c7a158e4469',
                'key_name' => 'global_sms',
                'live_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              36 => 
              array (
                'id' => 'b8992bd4-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'paymob_accept',
                'live_values' => '{"gateway":"paymob_accept","mode":"live","status":"0","callback_url":null,"api_key":"","iframe_id":"","integration_id":"","hmac":""}',
                'test_values' => '{"gateway":"paymob_accept","mode":"live","status":"0","callback_url":null,"api_key":"","iframe_id":"","integration_id":"","hmac":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Paymob accept","gateway_image":null}',
              ),
              37 => 
              array (
                'id' => 'c41c0dcd-d119-11ed-9f67-0c7a158e4469',
                'key_name' => 'maxicash',
                'live_values' => '{"gateway":"maxicash","mode":"test","status":"0","merchantId":"data","merchantPassword":"data"}',
                'test_values' => '{"gateway":"maxicash","mode":"test","status":"0","merchantId":"data","merchantPassword":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:49:15',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              38 => 
              array (
                'id' => 'c9249d17-cd60-11ed-b879-0c7a158e4469',
                'key_name' => 'pvit',
                'live_values' => '{"gateway":"pvit","mode":"test","status":"0","mc_tel_merchant": "","access_token": "", "mc_merchant_code": ""}',
                'test_values' => '{"gateway":"pvit","mode":"test","status":"0","mc_tel_merchant": "","access_token": "", "mc_merchant_code": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              39 => 
              array (
                'id' => 'cb0081ce-d775-11ed-96f4-0c7a158e4469',
                'key_name' => 'releans',
                'live_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 08:14:44',
                'additional_data' => '',
              ),
              40 => 
              array (
                'id' => 'd4f3f5f1-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'flutterwave',
                'live_values' => '{"gateway":"flutterwave","mode":"live","status":0,"secret_key":"","public_key":"","hash":""}',
                'test_values' => '{"gateway":"flutterwave","mode":"live","status":0,"secret_key":"","public_key":"","hash":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:41:03',
                'additional_data' => '{"gateway_title":"Flutterwave","gateway_image":null}',
              ),
              41 => 
              array (
                'id' => 'd822f1a5-c864-11ed-ac7a-0c7a158e4469',
                'key_name' => 'paystack',
                'live_values' => '{"gateway":"paystack","mode":"live","status":"0","callback_url":"https:\\/\\/api.paystack.co","public_key":null,"secret_key":null,"merchant_email":null}',
                'test_values' => '{"gateway":"paystack","mode":"live","status":"0","callback_url":"https:\\/\\/api.paystack.co","public_key":null,"secret_key":null,"merchant_email":null}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 10:20:45',
                'additional_data' => '{"gateway_title":"Paystack","gateway_image":null}',
              ),
              42 => 
              array (
                'id' => 'daec8d59-c893-11ed-ac7a-0c7a158e4469',
                'key_name' => 'xendit',
                'live_values' => '{"gateway":"xendit","mode":"test","status":"0","api_key":"data"}',
                'test_values' => '{"gateway":"xendit","mode":"test","status":"0","api_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:35:46',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              43 => 
              array (
                'id' => 'dc0f5fc9-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'worldpay',
                'live_values' => '{"gateway":"worldpay","mode":"test","status":"0","OrgUnitId":"data","jwt_issuer":"data","mac":"data","merchantCode":"data","xml_password":"data"}',
                'test_values' => '{"gateway":"worldpay","mode":"test","status":"0","OrgUnitId":"data","jwt_issuer":"data","mac":"data","merchantCode":"data","xml_password":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-12 12:35:26',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
              ),
              44 => 
              array (
                'id' => 'e0450278-d8eb-11ed-8249-0c7a158e4469',
                'key_name' => 'signal_wire',
                'live_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              45 => 
              array (
                'id' => 'e0450b40-d8eb-11ed-8249-0c7a158e4469',
                'key_name' => 'paradox',
                'live_values' => '{"gateway":"paradox","mode":"live","status":"0","api_key":"","sender_id":""}',
                'test_values' => '{"gateway":"paradox","mode":"live","status":"0","api_key":"","sender_id":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-10 07:14:01',
                'additional_data' => '',
              ),
              46 => 
              array (
                'id' => 'ea346efe-cdda-11ed-affe-0c7a158e4469',
                'key_name' => 'ssl_commerz',
                'live_values' => '{"gateway":"ssl_commerz","mode":"live","status":"0","store_id":"","store_password":""}',
                'test_values' => '{"gateway":"ssl_commerz","mode":"live","status":"0","store_id":"","store_password":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-30 09:43:49',
                'additional_data' => '{"gateway_title":"Ssl commerz","gateway_image":null}',
              ),
              47 => 
              array (
                'id' => 'eed88336-d8ec-11ed-8249-0c7a158e4469',
                'key_name' => 'hubtel',
                'live_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}',
                'test_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              48 => 
              array (
                'id' => 'f149c546-d8ea-11ed-8249-0c7a158e4469',
                'key_name' => 'viatech',
                'live_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}',
                'test_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
              49 => 
              array (
                'id' => 'f149cd9c-d8ea-11ed-8249-0c7a158e4469',
                'key_name' => '019_sms',
                'live_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}',
                'test_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '',
              ),
            );
        foreach ($chunks as $rows) {
            DB::table('addon_settings')->insert($rows);
        }

        Schema::enableForeignKeyConstraints();
    }
}
