<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class EmailTemplateTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('email_templates')->truncate();
        $chunks = [];
        $chunks[] =
            array (
              0 => 
              array (
                'id' => 1,
                'template_name' => 'order-received',
                'user_type' => 'admin',
                'template_design_name' => 'order-received',
                'title' => 'New Order Received',
                'body' => '<p><b>Hi {adminName},</b></p><p>We have sent you this email to notify that you have a new order.You will be able to see your orders after login to your panel.</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["icon", "product_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              1 => 
              array (
                'id' => 2,
                'template_name' => 'order-place',
                'user_type' => 'customer',
                'template_design_name' => 'order-place',
                'title' => 'Order # {orderId} Has Been Placed Successfully!',
                'body' => '<p><b>Hi {userName},</b></p><p>Your order from {shopName} has been placed to know the current status of your order click track order</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["icon", "product_information", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              2 => 
              array (
                'id' => 3,
                'template_name' => 'registration-verification',
                'user_type' => 'customer',
                'template_design_name' => 'registration-verification',
                'title' => 'Registration Verification',
                'body' => '<p><b>Hi {userName},</b></p><p>Your verification code is</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              3 => 
              array (
                'id' => 4,
                'template_name' => 'registration-from-pos',
                'user_type' => 'customer',
                'template_design_name' => 'registration-from-pos',
                'title' => 'Registration Complete',
                'body' => '<p><b>Hi {userName},</b></p><p>Thank you for joining  Shop.If you want to become a registered customer then reset your password below by using this email. Then you’ll be able to explore the website and app as a registered customer.</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_url", "button_content_status", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              4 => 
              array (
                'id' => 5,
                'template_name' => 'account-block',
                'user_type' => 'customer',
                'template_design_name' => 'account-block',
                'title' => 'Account Blocked',
                'body' => '<div><b>Hi {userName},</b></div><div><b><br></b></div><div>Your account has been blocked due to suspicious activity by the admin .To resolve this issue please contact with admin or support center. We apologize for any inconvenience caused.</div><div><br></div><div>Meanwhile, click here to visit theshop website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              5 => 
              array (
                'id' => 6,
                'template_name' => 'account-unblock',
                'user_type' => 'customer',
                'template_design_name' => 'account-unblock',
                'title' => 'Account Unblocked',
                'body' => '<div><b>Hi {userName},</b></div><div><b><br></b></div><div>Your account has been successfully unblocked. We appreciate your cooperation in resolving this issue. Thank you for your understanding and patience. </div><div><br></div><div>Meanwhile, click here to visit the shop website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              6 => 
              array (
                'id' => 7,
                'template_name' => 'digital-product-download',
                'user_type' => 'customer',
                'template_design_name' => 'digital-product-download',
                'title' => 'Congratulations',
                'body' => '<p>Thank you for choosing  shop! Your digital product is ready for download. To download your product use your email <b>{emailId}</b> and order # {orderId} below.</b><br></p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              7 => 
              array (
                'id' => 8,
                'template_name' => 'digital-product-otp',
                'user_type' => 'customer',
                'template_design_name' => 'digital-product-otp',
                'title' => 'Digital Product Download OTP Verification',
                'body' => '<p><b>Hi {userName},</b></p><p>Your verification code is</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:11',
                'updated_at' => '2025-02-17 23:23:11',
              ),
              8 => 
              array (
                'id' => 9,
                'template_name' => 'add-fund-to-wallet',
                'user_type' => 'customer',
                'template_design_name' => 'add-fund-to-wallet',
                'title' => 'Transaction Successful',
                'body' => '<div style=\\"text-align: center; \\">Amount successfully credited to your wallet .</div><div style=\\"text-align: center; \\"><br></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              9 => 
              array (
                'id' => 10,
                'template_name' => 'registration',
                'user_type' => 'vendor',
                'template_design_name' => 'registration',
                'title' => 'Registration Complete',
                'body' => '<div><b>Hi {vendorName},</b></div><div><b><br></b></div><div>Congratulation! Your registration request has been send to admin successfully! Please wait until admin reviewal. </div><div><br></div><div>meanwhile click here to visit the  Shop Website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              10 => 
              array (
                'id' => 11,
                'template_name' => 'registration-approved',
                'user_type' => 'vendor',
                'template_design_name' => 'registration-approved',
                'title' => 'Registration Approved',
                'body' => '<div><b>Hi {vendorName},</b></div><div><b><br></b></div><div>Your registration request has been approved by admin. Now you can complete your store setting and start selling your product on  Shop. </div><div><br></div><div>Meanwhile, click here to visit the shop website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              11 => 
              array (
                'id' => 12,
                'template_name' => 'registration-denied',
                'user_type' => 'vendor',
                'template_design_name' => 'registration-denied',
                'title' => 'Registration Denied',
                'body' => '<div><b>Hi {vendorName},</b></div><div><b><br></b></div><div>Your registration request has been denied by admin. Please contact with admin or support center if you have any queries.</div><div><br></div><div>Meanwhile, click here to visit the shop website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              12 => 
              array (
                'id' => 13,
                'template_name' => 'account-suspended',
                'user_type' => 'vendor',
                'template_design_name' => 'account-suspended',
                'title' => 'Account Suspended',
                'body' => '<div><b>Hi {vendorName},</b></div><div><b><br></b></div><div>Your account access has been suspended by admin.From now you can access your app and panel again Please contact us for any queries we’re always happy to help.</div><div><br></div><div>Meanwhile, click here to visit the shop website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              13 => 
              array (
                'id' => 14,
                'template_name' => 'account-activation',
                'user_type' => 'vendor',
                'template_design_name' => 'account-activation',
                'title' => 'Account Activation',
                'body' => '<div><b>Hi {vendorName},</b></div><div><b><br></b></div><div>Your account suspension has been revoked by admin. From now you can access your app and panel again Please contact us for any queries we’re always happy to help.</div><div><br></div><div>Meanwhile, click here to visit the shop website</div><div><font color=\\"#0000ff\\"> <a href=\\"https://dokankholo.com\\" target=\\"_blank\\">https://dokankholo.com</a></font></div>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              14 => 
              array (
                'id' => 15,
                'template_name' => 'forgot-password',
                'user_type' => 'vendor',
                'template_design_name' => 'forgot-password',
                'title' => 'Change Password Request',
                'body' => '<p><b>Hi {vendorName},</b></p><p>Please click the link below to change your password.</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              15 => 
              array (
                'id' => 16,
                'template_name' => 'order-received',
                'user_type' => 'vendor',
                'template_design_name' => 'order-received',
                'title' => 'New Order Received',
                'body' => '<p><b>Hi {vendorName},</b></p><p>We have sent you this email to notify that you have a new order.You will be able to see your orders after login to your panel.</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["icon", "product_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
              16 => 
              array (
                'id' => 17,
                'template_name' => 'reset-password-verification',
                'user_type' => 'delivery-man',
                'template_design_name' => 'reset-password-verification',
                'title' => 'OTP Verification For Password Reset',
                'body' => '<p><b>Hi {deliveryManName},</b></p><p>Your verification code is</p>',
                'banner_image' => '',
                'image' => '',
                'logo' => '',
                'button_name' => '',
                'button_url' => '',
                'footer_text' => 'Please contact us for any queries, we are always happy to help.',
                'copyright_text' => 'Copyright 2025 . All right reserved.',
                'pages' => NULL,
                'social_media' => NULL,
                'hide_field' => '["product_information", "order_information", "button_content", "banner_image"]',
                'button_content_status' => 1,
                'product_information_status' => 1,
                'order_information_status' => 1,
                'status' => 1,
                'created_at' => '2025-02-17 23:23:12',
                'updated_at' => '2025-02-17 23:23:12',
              ),
            );
        foreach ($chunks as $rows) {
            DB::table('email_templates')->insert($rows);
        }

        Schema::enableForeignKeyConstraints();
    }
}
